src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of prices on all products related to the Case</description>
        <label>Product Sum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>





    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Case_Product Junction table</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case_Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case_Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Case_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/CaseProductSumHelper.cls
public class CaseProductSumHelper {

    public static void updateRelatedCaseProductSum(List<Case_Product__c> caseProductChanges){
        Set<Id> relatedCaseIds = new Set<Id>();
        for(Case_Product__c caseProduct: caseProductChanges){
            relatedCaseIds.add(caseProduct.Case__c);
        }
        
        List<AggregateResult> updatedSums = [SELECT Case__c, SUM(Product__r.Price__c) productSum 
                                             FROM Case_Product__c 
                                             WHERE Case__c IN:relatedCaseIds 
                                             GROUP BY Case__c];
     	   
        Map<Id, Case> casesForUpdate = new Map<Id, Case>();
        
        //Set Product Sum for those cases that has records in junction table
        for(AggregateResult aggregateResultRow: updatedSums){
            Id caseId = (Id) aggregateResultRow.get('Case__c');
            Decimal productSum = (Decimal) aggregateResultRow.get('productSum');
            casesForUpdate.put(caseId, new Case(Id = caseId, Product_Sum__c = productSum));
        }
        
        //Set zero Product Sum for cases, which have no records in junction table
        for(Id caseId : relatedCaseIds){
            if(!casesForUpdate.containskey(caseId)){
                casesForUpdate.put(caseId, new Case(Id = caseId, Product_Sum__c = 0));
            }
        }
        
        update casesForUpdate.values();
    }
    
        public static void updateRelatedCaseProductSum(List<Product2> productChanges){
        Set<Id> relatedProductIds = new Set<Id>();
        for(Product2 currentProduct: productChanges){
            relatedProductIds.add(currentProduct.Id);
        }
        
        updateRelatedCaseProductSum([SELECT Id, Case__c, Product__c
                                     FROM Case_Product__c
                                     WHERE Product__c IN: relatedProductIds]);
    }
}