src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of prices on all products related to the Case</description>
        <label>Product Sum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>





    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Case_Product Junction table</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case_Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case_Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Case_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/CaseProductSumHelperTest.cls
@IsTest public with sharing class CaseProductSumHelperTest {
    
    private static final Decimal PRICE = 100;
   
    @testSetup
    static void setup(){
    	RecordType caseRecordType = [SELECT Id FROM RecordType WHERE Name = 'Product Inquiry' LIMIT 1];
    	
    	Case testCase = new Case(RecordTypeId= caseRecordType.Id, Status = 'New', Origin = 'Phone', Subject = 'testCase');
    	insert testCase;
    	
    	Product2 testProductOne = new Product2(Name = 'TestProductOne', price__c = PRICE);
    	insert testProductOne;
    	
    	Product2 TestProductTwo = new Product2(Name = 'TestProductTwo', price__c = (PRICE+PRICE));
    	insert testProductTwo;
    	
    	
    }
    
    @IsTest
    static void updateProductSumIncrease(){
        Case testCase = [SELECT Id FROM Case WHERE Subject = 'testCase'];
        Id testCaseId = testCase.Id;
		Product2 testProductOne = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductOne'];
        Product2 testProductTwo = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductTwo'];

		Case_Product__c CaseProductOne = new Case_product__c(Case__c = testCase.Id, Product__c = testProductOne.Id);
    	Case_Product__c CaseProductTwo = new Case_product__c(Case__c = testCase.Id, Product__c = testProductTwo.Id);
        List<Case_Product__c> caseProducts = new List<Case_product__c>();
    	caseProducts.add(CaseProductOne);
    	caseProducts.add(CaseProductTwo);
        
        Test.startTest();
    	insert caseProducts;
        Test.stopTest();
        
        Case resultCase = [SELECT Id, Product_Sum__c FROM Case  WHERE Id = :testCaseId];
    	System.assertEquals(resultCase.Product_Sum__c, testProductOne.Price__c + testProductTwo.Price__c);
		    	
    }
    
    @IsTest
    static void updateProductSumDecreaseToZero(){
         Case testCase = [SELECT Id FROM Case WHERE Subject = 'testCase'];
        Id testCaseId = testCase.Id;
		Product2 testProductOne = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductOne'];
        Product2 testProductTwo = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductTwo'];

		Case_Product__c CaseProductOne = new Case_product__c(Case__c = testCase.Id, Product__c = testProductOne.Id);
    	Case_Product__c CaseProductTwo = new Case_product__c(Case__c = testCase.Id, Product__c = testProductTwo.Id);
        List<Case_Product__c> caseProducts = new List<Case_product__c>();
    	caseProducts.add(CaseProductOne);
    	caseProducts.add(CaseProductTwo);
        insert caseProducts;
        
        Test.startTest();
    	delete caseProducts;
        Test.stopTest();
        
        Case resultCase = [SELECT Id, Product_Sum__c FROM Case  WHERE Id = :testCaseId];
    	System.assertEquals(resultCase.Product_Sum__c, 0);
	}
    
    @IsTest
    static void updateProductSumDecreasePartial(){
         Case testCase = [SELECT Id FROM Case WHERE Subject = 'testCase'];
        Id testCaseId = testCase.Id;
		Product2 testProductOne = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductOne'];
        Product2 testProductTwo = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductTwo'];

		Case_Product__c CaseProductOne = new Case_product__c(Case__c = testCase.Id, Product__c = testProductOne.Id);
    	Case_Product__c CaseProductTwo = new Case_product__c(Case__c = testCase.Id, Product__c = testProductTwo.Id);
        List<Case_Product__c> caseProducts = new List<Case_product__c>();
    	caseProducts.add(CaseProductOne);
    	caseProducts.add(CaseProductTwo);
        insert caseProducts;
        
        Test.startTest();
    	delete CaseProductOne;
        Test.stopTest();
        
        Case resultCase = [SELECT Id, Product_Sum__c FROM Case  WHERE Id = :testCaseId];
    	System.assertEquals(resultCase.Product_Sum__c, testProductTwo.Price__c);
	}
    
    @IsTest
    static void updateProductSumByChangeInProduct(){
         Case testCase = [SELECT Id FROM Case WHERE Subject = 'testCase'];
        Id testCaseId = testCase.Id;
		Product2 testProductOne = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductOne'];
        Product2 testProductTwo = [SELECT Id, Price__c FROM Product2 WHERE Name = 'TestProductTwo'];

		Case_Product__c CaseProductOne = new Case_product__c(Case__c = testCase.Id, Product__c = testProductOne.Id);
    	Case_Product__c CaseProductTwo = new Case_product__c(Case__c = testCase.Id, Product__c = testProductTwo.Id);
        List<Case_Product__c> caseProducts = new List<Case_product__c>();
    	caseProducts.add(CaseProductOne);
    	caseProducts.add(CaseProductTwo);
        insert caseProducts;
        
        Test.startTest();
        testProductOne.Price__c = testProductOne.Price__c+PRICE;
    	update testProductOne;
        Test.stopTest();
        
        Case resultCase = [SELECT Id, Product_Sum__c FROM Case  WHERE Id = :testCaseId];
    	System.assertEquals(resultCase.Product_Sum__c, testProductOne.Price__c+testProductTwo.Price__c);
    }
}