src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email_Send_Weekly__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If email has been sent this week,the field is true. Otherwise,the field is false.</description>
        <label>Email Send Weekly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Send__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If the field is true, the mail has been sent. If the field is false,the mail isn&apos;t sent today.</description>
        <label>Email Send Dayly</label>
        <type>Checkbox</type>
    </fields>





    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseWeeklyStatusChanger.cls
global class CaseWeeklyStatusChanger Implements Database.Batchable <sObject>{

global Database.queryLocator start(Database.BatchableContext bc) {
    String SOQL = 'SELECT Email_Send__c FROM Case';
    return Database.getQueryLocator(SOQL);
}

global void execute(Database.BatchableContext bc, List<sObject> scope) {
    list<Case> listToUpdate = new list<Case>();
    for(sObject s : scope)
    {
        Case obj = (Case) s; 
        obj.Email_Send_Weekly__c = false;
        listToUpdate.add(obj);
    }
    update listToUpdate; 

}

global void finish(Database.BatchableContext bc) {}
}