src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email_Send_Weekly__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If email has been sent this week,the field is true. Otherwise,the field is false.</description>
        <label>Email Send Weekly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Send__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If the field is true, the mail has been sent. If the field is false,the mail isn&apos;t sent today.</description>
        <label>Email Send Dayly</label>
        <type>Checkbox</type>
    </fields>





    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestChanger.cls
@isTest
public class TestChanger {
    
 static testMethod void testCaseEmailStatusChanger() {
        Test.startTest();
        Database.QueryLocator queryLocator;
        Database.BatchableContext batchContext;
        List<Case> casesList = new List<Case>();
        CaseEmailStatusChanger changer = new CaseEmailStatusChanger();
        queryLocator = changer.start(batchContext);
        
        Database.QueryLocatorIterator queryIterator =  queryLocator.iterator();
        while (queryIterator.hasNext())
        {
            Case caseObj = (Case)queryIterator.next(); 
            casesList.add(caseObj);
        }        
        
        changer.execute(batchContext, casesList);
     
        for(Case caseObj : casesList){
            System.assert(FALSE, caseObj.Email_Send__c);
        }
        changer.finish(batchContext);   
        Test.StopTest();     
    }
    
    static testMethod void testCaseWeeklyStatusChanger() {
        Test.startTest();
        Database.QueryLocator queryLocator;
        Database.BatchableContext batchContext;
        List<Case> casesList = new List<Case>();
        CaseWeeklyStatusChanger changer = new CaseWeeklyStatusChanger();
        queryLocator = changer.start(batchContext);
        
        Database.QueryLocatorIterator queryIterator =  queryLocator.iterator();
        while (queryIterator.hasNext())
        {
            Case caseObj = (Case)queryIterator.next(); 
            casesList.add(caseObj);
        }        
        
        changer.execute(batchContext, casesList);
        for(Case caseObj : casesList){
            System.assert(FALSE, caseObj.Email_Send_Weekly__c);
        }
        changer.finish(batchContext);   
        Test.StopTest();     
    }
        
}